---
title: "Практическая работа 004"
author: "dolgov18012005@yandex.ru"
format: 
  md:
    output-file: README.md
---

## Цель работы

1. Зекрепить практические навыки использования языка программирования R для обработки данных
2. Закрепить знания основных функций обработки данных экосистемы tidyverse языка R
3. Закрепить навыки исследования метаданных DNS трафика

## Исходные данные

1. Программное обеспечение Manjaro
2. Rstudio Desktop
3. Интерпретатор языка R 4.5.1

## Задание

Используя программный пакет dplyr, освоить анализ DNS логов с помощью языка программирования R.

## Ход работы

1. Подготовка данных \
    1.1. Импортируйте данные DNS – https://storage.yandexcloud.net/dataset.ctfsec/dns.zip \
    1.2. Добавьте пропущенные данные о структуре данных (назначении столбцов) \
    1.3. Преобразуйте данные в столбцах в нужный формат \
    1.4. Просмотрите общую структуру данных с помощью функции glimpse() \

2. Анализ \
    2.1. Сколько участников информационного обмена в сети Доброй Организации? \
    2.2. Какое соотношение участников обмена внутри сети и участников обращений к внешним ресурсам? \
    2.3. Найдите топ-10 участников сети, проявляющих наибольшую сетевую активность. \
    2.4. Найдите топ-10 доменов, к которым обращаются пользователи сети и соответственное количество обращений \
    2.5. Опеределите базовые статистические характеристики (функция summary() ) интервала времени между последовательными обращениями к топ-10 доменам. \
    2.6. Часто вредоносное программное обеспечение использует DNS канал в качестве канала управления, периодически отправляя запросы на подконтрольный злоумышленникам DNS сервер. По периодическим запросам на один и тот же домен можно выявить скрытый DNS канал. Есть ли такие IP адреса в исследуемом датасете? \
3. Обогащение данных \
    3.1. Определите местоположение (страну, город) и организацию-провайдера для топ-10 доменов. Для этого можно использовать сторонние сервисы, например http://ip-api.com (API-эндпоинт – http://ip-api.com/json).


### Шаг 1


