---
title: "Практическая работа 002"
author: "dolgov18012005@yandex.ru"
format: 
  md:
    output-file: README.md
---

## Цель работы

1. Развить практические навыки использования языка программирования R для обработки данных
2. Закрепить знания базовых типов данных языка R
3. Развить практические навыки использования функций обработки данных пакета `dplyr` – функции `select(), filter(), mutate(), arrange(), group_by()`

## Исходные данные

1. Программное обеспечение Manjaro
2. Rstudio Desktop
3. Интерпретатор языка R 4.5.1

## Задание

Используя программный пакет dplyr, освоить базовые
операции в языке программирования R.

## Ход работы

1. Проанализировать встроенный в пакет dplyr набор данных starwars с помощью языка R и ответить на вопросы:
    - Сколько строк в датафрейме?
    - Сколько столбцов в датафрейме?
    - Как просмотреть примерный вид датафрейма?
    - Сколько уникальных рас персонажей (species) представлено в данных?
    - Найти самого высокого персонажа.
    - Найти всех персонажей ниже 170
    - Подсчитать ИМТ (индекс массы тела) для всех персонажей.
    - Найти 10 самых “вытянутых” персонажей. “Вытянутость” оценить по отношению массы (mass) к росту (height) персонажей
    - Найти средний возраст персонажей каждой расы вселенной Звездных войн
    - Найти самый распространенный цвет глаз персонажей вселенной Звездных войн.
    - Подсчитать среднюю длину имени в каждой расе вселенной Звездных войн.
2. Оформить отчет в соответствии с шаблоном

### Шаг 1

Подключаем библиотеку dplyr

```{r}
library(dplyr)
```
    
#### Сколько строк в датафрейме?

```
> starwars %>% nrow()
[1] 87
```

#### Сколько столбцов в датафрейме?


```
> starwars %>% ncol()
[1] 14
```

#### Как просмотреть примерный вид датафрейма?

```
> starwars %>% glimpse()
Rows: 87
Columns: 14
$ name       <chr> "Luke Skywalker", "C-3PO", "R2-D2", "Darth Vader", "Leia Organa", "O…
$ height     <int> 172, 167, 96, 202, 150, 178, 165, 97, 183, 182, 188, 180, 228, 180, …
$ mass       <dbl> 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0, 32.0, 84.0, 77.0, 84.0, …
$ hair_color <chr> "blond", NA, NA, "none", "brown", "brown, grey", "brown", NA, "black…
$ skin_color <chr> "fair", "gold", "white, blue", "white", "light", "light", "light", "…
$ eye_color  <chr> "blue", "yellow", "red", "yellow", "brown", "blue", "blue", "red", "…
$ birth_year <dbl> 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, NA, 24.0, 57.0, 41.9, 64.…
$ sex        <chr> "male", "none", "none", "male", "female", "male", "female", "none", …
$ gender     <chr> "masculine", "masculine", "masculine", "masculine", "feminine", "mas…
$ homeworld  <chr> "Tatooine", "Tatooine", "Naboo", "Tatooine", "Alderaan", "Tatooine",…
$ species    <chr> "Human", "Droid", "Droid", "Human", "Human", "Human", "Human", "Droi…
$ films      <list> <"A New Hope", "The Empire Strikes Back", "Return of the Jedi", "Re…
$ vehicles   <list> <"Snowspeeder", "Imperial Speeder Bike">, <>, <>, <>, "Imperial Spe…
$ starships  <list> <"X-wing", "Imperial shuttle">, <>, <>, "TIE Advanced x1", <>, <>, …
```

#### Сколько уникальных рас персонажей (species) представлено в данных?

```
> starwars %>% select(., species) %>% filter(!is.na(species)) %>% unique(.) %>% count(.) |> knitr::kable(format = "markdown")
```

|  n|
|--:|
| 37|

#### Найти самого высокого персонажа.

```
> starwars %>% arrange(., desc(height)) %>% select(name) %>% slice(1)  |> knitr::kable(format = "markdown")
```

|name        |
|:-----------|
|Yarael Poof |


#### Найти всех персонажей ниже 170
 
```
> starwars %>% filter(height < 170) %>% select(., name, height)|> knitr::kable(format = "markdown")
```

|name                  | height|
|:---------------------|------:|
|C-3PO                 |    167|
|R2-D2                 |     96|
|Leia Organa           |    150|
|Beru Whitesun Lars    |    165|
|R5-D4                 |     97|
|Yoda                  |     66|
|Mon Mothma            |    150|
|Wicket Systri Warrick |     88|
|Nien Nunb             |    160|
|Watto                 |    137|
|Sebulba               |    112|
|Shmi Skywalker        |    163|
|Ratts Tyerel          |     79|
|Dud Bolt              |     94|
|Gasgano               |    122|
|Ben Quadinaros        |    163|
|Cordé                 |    157|
|Barriss Offee         |    166|
|Dormé                 |    165|
|Zam Wesell            |    168|
|Jocasta Nu            |    167|
|R4-P17                |     96|


#### Подсчитать ИМТ (индекс массы тела) для всех персонажей.

```
> starwars %>% mutate(., imt = mass / (height^2)) %>% select(., name, imt) |> knitr::kable(format = "markdown")
```

|name                  |       imt|
|:---------------------|---------:|
|Luke Skywalker        | 0.0026028|
|C-3PO                 | 0.0026892|
|R2-D2                 | 0.0034722|
|Darth Vader           | 0.0033330|
|Leia Organa           | 0.0021778|
|Owen Lars             | 0.0037874|
|Beru Whitesun Lars    | 0.0027548|
|R5-D4                 | 0.0034010|
|Biggs Darklighter     | 0.0025083|
|Obi-Wan Kenobi        | 0.0023246|
|Anakin Skywalker      | 0.0023766|
|Wilhuff Tarkin        |        NA|
|Chewbacca             | 0.0021545|
|Han Solo              | 0.0024691|
|Greedo                | 0.0024725|
|Jabba Desilijic Tiure | 0.0443429|
|Wedge Antilles        | 0.0026644|
|Jek Tono Porkins      | 0.0033951|
|Yoda                  | 0.0039027|
|Palpatine             | 0.0025952|
|Boba Fett             | 0.0023351|
|IG-88                 | 0.0035000|
|Bossk                 | 0.0031302|
|Lando Calrissian      | 0.0025216|
|Lobot                 | 0.0025796|
|Ackbar                | 0.0025617|
|Mon Mothma            |        NA|
|Arvel Crynyd          |        NA|
|Wicket Systri Warrick | 0.0025826|
|Nien Nunb             | 0.0026563|
|Qui-Gon Jinn          | 0.0023893|
|Nute Gunray           | 0.0024670|
|Finis Valorum         |        NA|
|Padmé Amidala         | 0.0013148|
|Jar Jar Binks         | 0.0017180|
|Roos Tarpals          | 0.0016342|
|Rugor Nass            |        NA|
|Ric Olié              |        NA|
|Watto                 |        NA|
|Sebulba               | 0.0031888|
|Quarsh Panaka         |        NA|
|Shmi Skywalker        |        NA|
|Darth Maul            | 0.0026122|
|Bib Fortuna           |        NA|
|Ayla Secura           | 0.0017359|
|Ratts Tyerel          | 0.0024035|
|Dud Bolt              | 0.0050928|
|Gasgano               |        NA|
|Ben Quadinaros        | 0.0024465|
|Mace Windu            | 0.0023766|
|Ki-Adi-Mundi          | 0.0020916|
|Kit Fisto             | 0.0022647|
|Eeth Koth             |        NA|
|Adi Gallia            | 0.0014768|
|Saesee Tiin           |        NA|
|Yarael Poof           |        NA|
|Plo Koon              | 0.0022635|
|Mas Amedda            |        NA|
|Gregar Typho          | 0.0024836|
|Cordé                 |        NA|
|Cliegg Lars           |        NA|
|Poggle the Lesser     | 0.0023888|
|Luminara Unduli       | 0.0019446|
|Barriss Offee         | 0.0018145|
|Dormé                 |        NA|
|Dooku                 | 0.0021477|
|Bail Prestor Organa   |        NA|
|Jango Fett            | 0.0023590|
|Zam Wesell            | 0.0019487|
|Dexter Jettster       | 0.0026018|
|Lama Su               | 0.0016781|
|Taun We               |        NA|
|Jocasta Nu            |        NA|
|R4-P17                |        NA|
|Wat Tambor            | 0.0012886|
|San Hill              |        NA|
|Shaak Ti              | 0.0017990|
|Grievous              | 0.0034079|
|Tarfful               | 0.0024837|
|Raymus Antilles       | 0.0022352|
|Sly Moore             | 0.0015150|
|Tion Medon            | 0.0018852|
|Finn                  |        NA|
|Rey                   |        NA|
|Poe Dameron           |        NA|
|BB8                   |        NA|
|Captain Phasma        |        NA|


#### Найти 10 самых “вытянутых” персонажей. “Вытянутость” оценить по отношению массы (mass) к росту (height) персонажей
 
```
> starwars %>% mutate(., vut = mass / height) %>% select(., name, vut) %>% arrange(., vut) %>% slice(., 1:10) |> knitr::kable(format = "markdown")
```

|name                  |       vut|
|:---------------------|---------:|
|Ratts Tyerel          | 0.1898734|
|Wicket Systri Warrick | 0.2272727|
|Padmé Amidala         | 0.2432432|
|Wat Tambor            | 0.2487047|
|Yoda                  | 0.2575758|
|Sly Moore             | 0.2696629|
|Adi Gallia            | 0.2717391|
|Barriss Offee         | 0.3012048|
|Ayla Secura           | 0.3089888|
|Shaak Ti              | 0.3202247|


#### Найти средний возраст персонажей каждой расы вселенной Звездных войн

```
> starwars %>% filter(!is.na(birth_year)) %>% filter(!is.na(species)) %>% group_by(., species) %>% summarize(mean_age = mean(100 - birth_year)) %>% select(., species, mean_age) |> knitr::kable(format = "markdown")
```

|species        |   mean_age|
|:--------------|----------:|
|Cerean         |    8.00000|
|Droid          |   46.66667|
|Ewok           |   92.00000|
|Gungan         |   48.00000|
|Human          |   46.25769|
|Hutt           | -500.00000|
|Kel Dor        |   78.00000|
|Mirialan       |   51.00000|
|Mon Calamari   |   59.00000|
|Rodian         |   56.00000|
|Trandoshan     |   47.00000|
|Twi'lek        |   52.00000|
|Wookiee        | -100.00000|
|Yoda's species | -796.00000|
|Zabrak         |   46.00000|


#### Найти самый распространенный цвет глаз персонажей вселенной Звездных войн.

```
> starwars %>% group_by(., eye_color) %>% summarize(count_colors = n()) %>% arrange(., desc(count_colors)) %>% select(., eye_color) %>% slice(1)
# A tibble: 1 × 1
  eye_color
  <chr>    
1 brown
```

#### Подсчитать среднюю длину имени в каждой расе вселенной Звездных войн.

```
> starwars %>% filter(!is.na(species)) %>% group_by(., species) %>% summarize(mean_len = mean(nchar(name))) %>% select(., species, mean_len) |> knitr::kable(format = "markdown")
```

|species        |  mean_len|
|:--------------|---------:|
|Aleena         | 12.000000|
|Besalisk       | 15.000000|
|Cerean         | 12.000000|
|Chagrian       | 10.000000|
|Clawdite       | 10.000000|
|Droid          |  4.833333|
|Dug            |  7.000000|
|Ewok           | 21.000000|
|Geonosian      | 17.000000|
|Gungan         | 11.666667|
|Human          | 11.342857|
|Hutt           | 21.000000|
|Iktotchi       | 11.000000|
|Kaleesh        |  8.000000|
|Kaminoan       |  7.000000|
|Kel Dor        |  8.000000|
|Mirialan       | 14.000000|
|Mon Calamari   |  6.000000|
|Muun           |  8.000000|
|Nautolan       |  9.000000|
|Neimodian      | 11.000000|
|Pau'an         | 10.000000|
|Quermian       | 11.000000|
|Rodian         |  6.000000|
|Skakoan        | 10.000000|
|Sullustan      |  9.000000|
|Tholothian     | 10.000000|
|Togruta        |  8.000000|
|Toong          | 14.000000|
|Toydarian      |  5.000000|
|Trandoshan     |  5.000000|
|Twi'lek        | 11.000000|
|Vulptereen     |  8.000000|
|Wookiee        |  8.000000|
|Xexto          |  7.000000|
|Yoda's species |  4.000000|
|Zabrak         |  9.500000|


### Шаг 2

Отчёт написан и оформлен

