---
title: "Практическая работа 007"
author: "dolgov18012005@yandex.ru"
format: 
  md:
    output-file: README.md
---

## Цель работы

1.  Закрепить навыки исследования данных журнала Windows Active Directory
2.  Изучить структуру журнала системы Windows Active Directory
3.  Закрепить практические навыки использования языка программирования R для обработки данных
4.  Закрепить знания основных функций обработки данных экосистемы tidyverse языка R


## Исходные данные

1.  Программное обеспечение Manjaro
2.  Rstudio Desktop
3.  Интерпретатор языка R 4.5.1

## Задание

Используя программный пакет dplyr языка программирования R провести анализ журналов и ответить на вопросы.

## Ход работы

1.  Подготовка данных  \
    1.1. Импортируйте данные в R. Это можно выполнить с помощью jsonlite::stream_in(file()) . Датасет находится по адресу https://storage.yandexcloud.net/iamcth-data/dataset.tar.gz \
    1.2. Привести датасеты в вид “аккуратных данных”, преобразовать типы столбцов в соответствии с типом данных  \
    1.3. Просмотрите общую структуру данных с помощью функции glimpse()  

2.  Анализ  \
    2.1. Раскройте датафрейм избавившись от вложенных датафреймов. Для обнаружения таких можно использовать функцию dplyr::glimpse() , а для раскрытия вложенности – tidyr::unnest() . Обратите внимание, что при раскрытии теряются внешние названия колонок – это можно предотвратить если использовать параметр tidyr::unnest(..., names_sep = ).\
    2.2. Минимизируйте количество колонок в датафрейме – уберите колоки с единственным значением параметра. \
    2.3. Какое количество хостов представлено в данном датасете? \
    2.4. Подготовьте датафрейм с расшифровкой Windows Event_ID, приведите типы данных к типу их значений. \
    2.5. Есть ли в логе события с высоким и средним уровнем значимости? Сколько их?\ 

